last_year_data = {
    'Голы': {'away_collections': [{'away_command': 'West Ham(14)',
                                   'away_command_individual_total': '1',
                                   'dmY': '28.05.2023',
                                   'home_command': 'Leicester(18)',
                                   'home_command_individual_total': '2'},
                                  {'away_command': 'Leeds(18)',
                                   'away_command_individual_total': '1',
                                   'dmY': '21.05.2023',
                                   'home_command': 'West Ham(15)',
                                   'home_command_individual_total': '3'},
                                  {'away_command': 'West Ham(15)',
                                   'away_command_individual_total': '0',
                                   'dmY': '14.05.2023',
                                   'home_command': 'Brentford(10)',
                                   'home_command_individual_total': '2'},
                                  {'away_command': 'Man Utd(4)',
                                   'away_command_individual_total': '0',
                                   'dmY': '07.05.2023',
                                   'home_command': 'West Ham(15)',
                                   'home_command_individual_total': '1'},
                                  {'away_command': 'West Ham(15)',
                                   'away_command_individual_total': '0',
                                   'dmY': '03.05.2023',
                                   'home_command': 'Man City(2)',
                                   'home_command_individual_total': '3'},
                                  {'away_command': 'West Ham(15)',
                                   'away_command_individual_total': '3',
                                   'dmY': '29.04.2023',
                                   'home_command': 'Crystal Pa(12)',
                                   'home_command_individual_total': '4'},
                                  {'away_command': 'Liverpool(7)',
                                   'away_command_individual_total': '2',
                                   'dmY': '26.04.2023',
                                   'home_command': 'West Ham(14)',
                                   'home_command_individual_total': '1'},
                                  {'away_command': 'West Ham(15)',
                                   'away_command_individual_total': '4',
                                   'dmY': '23.04.2023',
                                   'home_command': 'Bournemout(14)',
                                   'home_command_individual_total': '0'},
                                  {'away_command': 'Arsenal(1)',
                                   'away_command_individual_total': '2',
                                   'dmY': '16.04.2023',
                                   'home_command': 'West Ham(15)',
                                   'home_command_individual_total': '2'},
                                  {'away_command': 'West Ham(15)',
                                   'away_command_individual_total': '1',
                                   'dmY': '08.04.2023',
                                   'home_command': 'Fulham(10)',
                                   'home_command_individual_total': '0'},
                                  {'away_command': 'Newcastle(3)',
                                   'away_command_individual_total': '5',
                                   'dmY': '05.04.2023',
                                   'home_command': 'West Ham(15)',
                                   'home_command_individual_total': '1'},
                                  {'away_command': 'Southampto(20)',
                                   'away_command_individual_total': '0',
                                   'dmY': '02.04.2023',
                                   'home_command': 'West Ham(19)',
                                   'home_command_individual_total': '1'},
                                  {'away_command': 'Aston Vill(11)',
                                   'away_command_individual_total': '1',
                                   'dmY': '12.03.2023',
                                   'home_command': 'West Ham(18)',
                                   'home_command_individual_total': '1'},
                                  {'away_command': 'West Ham(16)',
                                   'away_command_individual_total': '0',
                                   'dmY': '04.03.2023',
                                   'home_command': 'Brighton(8)',
                                   'home_command_individual_total': '4'},
                                  {'away_command': 'Nottingham(13)',
                                   'away_command_individual_total': '0',
                                   'dmY': '25.02.2023',
                                   'home_command': 'West Ham(18)',
                                   'home_command_individual_total': '4'},
                                  {'away_command': 'West Ham(18)',
                                   'away_command_individual_total': '0',
                                   'dmY': '19.02.2023',
                                   'home_command': 'Tottenham(5)',
                                   'home_command_individual_total': '2'},
                                  {'away_command': 'Chelsea(9)',
                                   'away_command_individual_total': '1',
                                   'dmY': '11.02.2023',
                                   'home_command': 'West Ham(16)',
                                   'home_command_individual_total': '1'},
                                  {'away_command': 'West Ham(16)',
                                   'away_command_individual_total': '1',
                                   'dmY': '04.02.2023',
                                   'home_command': 'Newcastle(3)',
                                   'home_command_individual_total': '1'},
                                  {'away_command': 'Everton(19)',
                                   'away_command_individual_total': '0',
                                   'dmY': '21.01.2023',
                                   'home_command': 'West Ham(18)',
                                   'home_command_individual_total': '2'},
                                  {'away_command': 'West Ham(17)',
                                   'away_command_individual_total': '0',
                                   'dmY': '14.01.2023',
                                   'home_command': 'Wolves(19)',
                                   'home_command_individual_total': '1'},
                                  {'away_command': 'West Ham(17)',
                                   'away_command_individual_total': '2',
                                   'dmY': '04.01.2023',
                                   'home_command': 'Leeds(14)',
                                   'home_command_individual_total': '2'},
                                  {'away_command': 'Brentford(10)',
                                   'away_command_individual_total': '2',
                                   'dmY': '30.12.2022',
                                   'home_command': 'West Ham(16)',
                                   'home_command_individual_total': '0'},
                                  {'away_command': 'West Ham(16)',
                                   'away_command_individual_total': '1',
                                   'dmY': '26.12.2022',
                                   'home_command': 'Arsenal(1)',
                                   'home_command_individual_total': '3'},
                                  {'away_command': 'Leicester(14)',
                                   'away_command_individual_total': '2',
                                   'dmY': '12.11.2022',
                                   'home_command': 'West Ham(15)',
                                   'home_command_individual_total': '0'},
                                  {'away_command': 'Crystal Pa(10)',
                                   'away_command_individual_total': '2',
                                   'dmY': '06.11.2022',
                                   'home_command': 'West Ham(13)',
                                   'home_command_individual_total': '1'},
                                  {'away_command': 'West Ham(12)',
                                   'away_command_individual_total': '0',
                                   'dmY': '30.10.2022',
                                   'home_command': 'Man Utd(6)',
                                   'home_command_individual_total': '1'},
                                  {'away_command': 'Bournemout(13)',
                                   'away_command_individual_total': '0',
                                   'dmY': '24.10.2022',
                                   'home_command': 'West Ham(16)',
                                   'home_command_individual_total': '2'},
                                  {'away_command': 'West Ham(13)',
                                   'away_command_individual_total': '0',
                                   'dmY': '19.10.2022',
                                   'home_command': 'Liverpool(8)',
                                   'home_command_individual_total': '1'},
                                  {'away_command': 'West Ham(12)',
                                   'away_command_individual_total': '1',
                                   'dmY': '16.10.2022',
                                   'home_command': 'Southampto(18)',
                                   'home_command_individual_total': '1'},
                                  {'away_command': 'Fulham(9)',
                                   'away_command_individual_total': '1',
                                   'dmY': '09.10.2022',
                                   'home_command': 'West Ham(15)',
                                   'home_command_individual_total': '3'},
                                  {'away_command': 'Wolves(17)',
                                   'away_command_individual_total': '0',
                                   'dmY': '01.10.2022',
                                   'home_command': 'West Ham(18)',
                                   'home_command_individual_total': '2'},
                                  {'away_command': 'West Ham(18)',
                                   'away_command_individual_total': '0',
                                   'dmY': '18.09.2022',
                                   'home_command': 'Everton(17)',
                                   'home_command_individual_total': '1'},
                                  {'away_command': 'West Ham(14)',
                                   'away_command_individual_total': '1',
                                   'dmY': '03.09.2022',
                                   'home_command': 'Chelsea(10)',
                                   'home_command_individual_total': '2'},
                                  {'away_command': 'Tottenham(3)',
                                   'away_command_individual_total': '1',
                                   'dmY': '31.08.2022',
                                   'home_command': 'West Ham(16)',
                                   'home_command_individual_total': '1'},
                                  {'away_command': 'West Ham(20)',
                                   'away_command_individual_total': '1',
                                   'dmY': '28.08.2022',
                                   'home_command': 'Aston Vill(15)',
                                   'home_command_individual_total': '0'},
                                  {'away_command': 'Brighton(8)',
                                   'away_command_individual_total': '2',
                                   'dmY': '21.08.2022',
                                   'home_command': 'West Ham(19)',
                                   'home_command_individual_total': '0'},
                                  {'away_command': 'West Ham(16)',
                                   'away_command_individual_total': '0',
                                   'dmY': '14.08.2022',
                                   'home_command': 'Nottingham(18)',
                                   'home_command_individual_total': '1'},
                                  {'away_command': 'Man City',
                                   'away_command_individual_total': '2',
                                   'dmY': '07.08.2022',
                                   'home_command': 'West Ham',
                                   'home_command_individual_total': '0'}],
             'home_collections': [{'away_command': 'Man City(1)',
                                   'away_command_individual_total': '0',
                                   'dmY': '28.05.2023',
                                   'home_command': 'Brentford(9)',
                                   'home_command_individual_total': '1'},
                                  {'away_command': 'Brentford(9)',
                                   'away_command_individual_total': '3',
                                   'dmY': '20.05.2023',
                                   'home_command': 'Tottenham(7)',
                                   'home_command_individual_total': '1'},
                                  {'away_command': 'West Ham(15)',
                                   'away_command_individual_total': '0',
                                   'dmY': '14.05.2023',
                                   'home_command': 'Brentford(10)',
                                   'home_command_individual_total': '2'},
                                  {'away_command': 'Brentford(9)',
                                   'away_command_individual_total': '0',
                                   'dmY': '06.05.2023',
                                   'home_command': 'Liverpool(5)',
                                   'home_command_individual_total': '1'},
                                  {'away_command': 'Nottingham(17)',
                                   'away_command_individual_total': '1',
                                   'dmY': '29.04.2023',
                                   'home_command': 'Brentford(9)',
                                   'home_command_individual_total': '2'},
                                  {'away_command': 'Brentford(10)',
                                   'away_command_individual_total': '2',
                                   'dmY': '26.04.2023',
                                   'home_command': 'Chelsea(11)',
                                   'home_command_individual_total': '0'},
                                  {'away_command': 'Aston Vill(6)',
                                   'away_command_individual_total': '1',
                                   'dmY': '22.04.2023',
                                   'home_command': 'Brentford(9)',
                                   'home_command_individual_total': '1'},
                                  {'away_command': 'Brentford(9)',
                                   'away_command_individual_total': '0',
                                   'dmY': '15.04.2023',
                                   'home_command': 'Wolves(13)',
                                   'home_command_individual_total': '2'},
                                  {'away_command': 'Newcastle(3)',
                                   'away_command_individual_total': '2',
                                   'dmY': '08.04.2023',
                                   'home_command': 'Brentford(9)',
                                   'home_command_individual_total': '1'},
                                  {'away_command': 'Brentford(9)',
                                   'away_command_individual_total': '0',
                                   'dmY': '05.04.2023',
                                   'home_command': 'Man Utd(5)',
                                   'home_command_individual_total': '1'},
                                  {'away_command': 'Brentford(8)',
                                   'away_command_individual_total': '3',
                                   'dmY': '01.04.2023',
                                   'home_command': 'Brighton(7)',
                                   'home_command_individual_total': '3'},
                                  {'away_command': 'Leicester(16)',
                                   'away_command_individual_total': '1',
                                   'dmY': '18.03.2023',
                                   'home_command': 'Brentford(8)90',
                                   'home_command_individual_total': '1'},
                                  {'away_command': 'Brentford(9)',
                                   'away_command_individual_total': '2',
                                   'dmY': '15.03.2023',
                                   'home_command': 'Southampto(20)',
                                   'home_command_individual_total': '0'},
                                  {'away_command': 'Brentford(9)',
                                   'away_command_individual_total': '0',
                                   'dmY': '11.03.2023',
                                   'home_command': 'Everton(18)',
                                   'home_command_individual_total': '1'},
                                  {'away_command': 'Fulham(7)',
                                   'away_command_individual_total': '2',
                                   'dmY': '06.03.2023',
                                   'home_command': 'Brentford(9)',
                                   'home_command_individual_total': '3'},
                                  {'away_command': 'Crystal Pa(12)',
                                   'away_command_individual_total': '1',
                                   'dmY': '18.02.2023',
                                   'home_command': 'Brentford(8)',
                                   'home_command_individual_total': '1'},
                                  {'away_command': 'Brentford(7)',
                                   'away_command_individual_total': '1',
                                   'dmY': '11.02.2023',
                                   'home_command': 'Arsenal(1)',
                                   'home_command_individual_total': '1'},
                                  {'away_command': 'Southampto(20)',
                                   'away_command_individual_total': '0',
                                   'dmY': '04.02.2023',
                                   'home_command': 'Brentford(8)',
                                   'home_command_individual_total': '3'},
                                  {'away_command': 'Brentford(9)',
                                   'away_command_individual_total': '0',
                                   'dmY': '22.01.2023',
                                   'home_command': 'Leeds(16)',
                                   'home_command_individual_total': '0'},
                                  {'away_command': 'Bournemout(16)',
                                   'away_command_individual_total': '0',
                                   'dmY': '14.01.2023',
                                   'home_command': 'Brentford(9)',
                                   'home_command_individual_total': '2'},
                                  {'away_command': 'Liverpool(6)',
                                   'away_command_individual_total': '1',
                                   'dmY': '02.01.2023',
                                   'home_command': 'Brentford(10)',
                                   'home_command_individual_total': '3'},
                                  {'away_command': 'Brentford(10)',
                                   'away_command_individual_total': '2',
                                   'dmY': '30.12.2022',
                                   'home_command': 'West Ham(16)',
                                   'home_command_individual_total': '0'},
                                  {'away_command': 'Tottenham(4)',
                                   'away_command_individual_total': '2',
                                   'dmY': '26.12.2022',
                                   'home_command': 'Brentford(9)',
                                   'home_command_individual_total': '2'},
                                  {'away_command': 'Brentford(11)',
                                   'away_command_individual_total': '2',
                                   'dmY': '12.11.2022',
                                   'home_command': 'Man City(2)',
                                   'home_command_individual_total': '1'},
                                  {'away_command': 'Brentford(11)',
                                   'away_command_individual_total': '2',
                                   'dmY': '05.11.2022',
                                   'home_command': 'Nottingham(20)',
                                   'home_command_individual_total': '2'},
                                  {'away_command': 'Wolves(19)90',
                                   'away_command_individual_total': '1',
                                   'dmY': '29.10.2022',
                                   'home_command': 'Brentford(11)',
                                   'home_command_individual_total': '1'},
                                  {'away_command': 'Brentford(10)',
                                   'away_command_individual_total': '0',
                                   'dmY': '23.10.2022',
                                   'home_command': 'Aston Vill(17)',
                                   'home_command_individual_total': '4'},
                                  {'away_command': 'Chelsea(4)',
                                   'away_command_individual_total': '0',
                                   'dmY': '19.10.2022',
                                   'home_command': 'Brentford(9)',
                                   'home_command_individual_total': '0'},
                                  {'away_command': 'Brighton(7)',
                                   'away_command_individual_total': '0',
                                   'dmY': '14.10.2022',
                                   'home_command': 'Brentford(12)',
                                   'home_command_individual_total': '2'},
                                  {'away_command': 'Brentford(10)',
                                   'away_command_individual_total': '1',
                                   'dmY': '08.10.2022',
                                   'home_command': 'Newcastle(7)',
                                   'home_command_individual_total': '5'},
                                  {'away_command': 'Brentford(9)',
                                   'away_command_individual_total': '0',
                                   'dmY': '01.10.2022',
                                   'home_command': 'Bournemout(12)',
                                   'home_command_individual_total': '0'},
                                  {'away_command': 'Arsenal(3)',
                                   'away_command_individual_total': '3',
                                   'dmY': '18.09.2022',
                                   'home_command': 'Brentford(9)',
                                   'home_command_individual_total': '0'},
                                  {'away_command': 'Leeds(7)',
                                   'away_command_individual_total': '2',
                                   'dmY': '03.09.2022',
                                   'home_command': 'Brentford(11)',
                                   'home_command_individual_total': '5'},
                                  {'away_command': 'Brentford(10)',
                                   'away_command_individual_total': '1',
                                   'dmY': '30.08.2022',
                                   'home_command': 'Crystal Pa(12)',
                                   'home_command_individual_total': '1'},
                                  {'away_command': 'Everton(17)',
                                   'away_command_individual_total': '1',
                                   'dmY': '27.08.2022',
                                   'home_command': 'Brentford(8)',
                                   'home_command_individual_total': '1'},
                                  {'away_command': 'Brentford(3)',
                                   'away_command_individual_total': '2',
                                   'dmY': '20.08.2022',
                                   'home_command': 'Fulham(13)',
                                   'home_command_individual_total': '3'},
                                  {'away_command': 'Man Utd(15)',
                                   'away_command_individual_total': '0',
                                   'dmY': '13.08.2022',
                                   'home_command': 'Brentford(10)',
                                   'home_command_individual_total': '4'},
                                  {'away_command': 'Brentford',
                                   'away_command_individual_total': '2',
                                   'dmY': '07.08.2022',
                                   'home_command': 'Leicester',
                                   'home_command_individual_total': '2'}]}}
league_data = {'current_season': {'goals': [{'avg_individual_team': '2.6',
                                             'avg_individual_team_against': '0.84',
                                             'avg_overall_total': '3.44',
                                             'games_played': '50',
                                             'points': '119',
                                             'team_name': 'Man '
                                                          'City',
                                             'team_position': '1'},
                                            {'avg_individual_team': '2.12',
                                             'avg_individual_team_against': '1.24',
                                             'avg_overall_total': '3.36',
                                             'games_played': '50',
                                             'points': '102',
                                             'team_name': 'Arsenal',
                                             'team_position': '2'},
                                            {'avg_individual_team': '1.98',
                                             'avg_individual_team_against': '1.06',
                                             'avg_overall_total': '3.04',
                                             'games_played': '50',
                                             'points': '99',
                                             'team_name': 'Liverpool',
                                             'team_position': '3'},
                                            {'avg_individual_team': '1.64',
                                             'avg_individual_team_against': '0.98',
                                             'avg_overall_total': '2.62',
                                             'games_played': '50',
                                             'points': '92',
                                             'team_name': 'Newcastle',
                                             'team_position': '4'},
                                            {'avg_individual_team': '1.42',
                                             'avg_individual_team_against': '1.32',
                                             'avg_overall_total': '2.74',
                                             'games_played': '50',
                                             'points': '87',
                                             'team_name': 'Man '
                                                          'Utd',
                                             'team_position': '5'},
                                            {'avg_individual_team': '1.98',
                                             'avg_individual_team_against': '1.42',
                                             'avg_overall_total': '3.4',
                                             'games_played': '50',
                                             'points': '86',
                                             'team_name': 'Tottenham',
                                             'team_position': '6'},
                                            {'avg_individual_team': '1.58',
                                             'avg_individual_team_against': '1.2',
                                             'avg_overall_total': '2.78',
                                             'games_played': '50',
                                             'points': '81',
                                             'team_name': 'Brentford',
                                             'team_position': '7'},
                                            {'avg_individual_team': '1.78',
                                             'avg_individual_team_against': '1.34',
                                             'avg_overall_total': '3.12',
                                             'games_played': '50',
                                             'points': '80',
                                             'team_name': 'Brighton',
                                             'team_position': '8'},
                                            {'avg_individual_team': '1.32',
                                             'avg_individual_team_against': '1.26',
                                             'avg_overall_total': '2.58',
                                             'games_played': '50',
                                             'points': '73',
                                             'team_name': 'Aston '
                                                          'Villa',
                                             'team_position': '9'},
                                            {'avg_individual_team': '1.22',
                                             'avg_individual_team_against': '1.24',
                                             'avg_overall_total': '2.46',
                                             'games_played': '50',
                                             'points': '65',
                                             'team_name': 'Chelsea',
                                             'team_position': '10'},
                                            {'avg_individual_team': '1.08',
                                             'avg_individual_team_against': '1.16',
                                             'avg_overall_total': '2.24',
                                             'games_played': '50',
                                             'points': '64',
                                             'team_name': 'Crystal '
                                                          'Palace',
                                             'team_position': '11'},
                                            {'avg_individual_team': '1.22',
                                             'avg_individual_team_against': '1.48',
                                             'avg_overall_total': '2.7',
                                             'games_played': '50',
                                             'points': '57',
                                             'team_name': 'Fulham',
                                             'team_position': '12'},
                                            {'avg_individual_team': '1.14',
                                             'avg_individual_team_against': '1.44',
                                             'avg_overall_total': '2.58',
                                             'games_played': '50',
                                             'points': '54',
                                             'team_name': 'West '
                                                          'Ham',
                                             'team_position': '13'},
                                            {'avg_individual_team': '1.46',
                                             'avg_individual_team_against': '1.64',
                                             'avg_overall_total': '3.1',
                                             'games_played': '50',
                                             'points': '53',
                                             'team_name': 'Leicester',
                                             'team_position': '14'},
                                            {'avg_individual_team': '0.98',
                                             'avg_individual_team_against': '1.52',
                                             'avg_overall_total': '2.5',
                                             'games_played': '50',
                                             'points': '53',
                                             'team_name': 'Everton',
                                             'team_position': '15'},
                                            {'avg_individual_team': '0.9',
                                             'avg_individual_team_against': '1.6',
                                             'avg_overall_total': '2.5',
                                             'games_played': '50',
                                             'points': '52',
                                             'team_name': 'Wolves',
                                             'team_position': '16'},
                                            {'avg_individual_team': '1.02',
                                             'avg_individual_team_against': '1.92',
                                             'avg_overall_total': '2.94',
                                             'games_played': '50',
                                             'points': '47',
                                             'team_name': 'Bournemouth',
                                             'team_position': '17'},
                                            {'avg_individual_team': '0.98',
                                             'avg_individual_team_against': '1.48',
                                             'avg_overall_total': '2.46',
                                             'games_played': '50',
                                             'points': '46',
                                             'team_name': 'Burnley',
                                             'team_position': '18'},
                                            {'avg_individual_team': '1.22',
                                             'avg_individual_team_against': '1.94',
                                             'avg_overall_total': '3.16',
                                             'games_played': '50',
                                             'points': '46',
                                             'team_name': 'Leeds',
                                             'team_position': '19'},
                                            {'avg_individual_team': '1',
                                             'avg_individual_team_against': '1.79',
                                             'avg_overall_total': '2.79',
                                             'games_played': '38',
                                             'points': '38',
                                             'team_name': 'Nottingham '
                                                          'Forest',
                                             'team_position': '20'},
                                            {'avg_individual_team': '0.62',
                                             'avg_individual_team_against': '1.56',
                                             'avg_overall_total': '2.18',
                                             'games_played': '50',
                                             'points': '38',
                                             'team_name': 'Sheff '
                                                          'Utd',
                                             'team_position': '21'},
                                            {'avg_individual_team': '0.9',
                                             'avg_individual_team_against': '1.9',
                                             'avg_overall_total': '2.8',
                                             'games_played': '50',
                                             'points': '37',
                                             'team_name': 'West '
                                                          'Brom',
                                             'team_position': '22'},
                                            {'avg_individual_team': '0.89',
                                             'avg_individual_team_against': '1.82',
                                             'avg_overall_total': '2.71',
                                             'games_played': '38',
                                             'points': '34',
                                             'team_name': 'Cardiff',
                                             'team_position': '23'},
                                            {'avg_individual_team': '0.74',
                                             'avg_individual_team_against': '1.47',
                                             'avg_overall_total': '2.21',
                                             'games_played': '38',
                                             'points': '33',
                                             'team_name': 'Swansea',
                                             'team_position': '24'},
                                            {'avg_individual_team': '0.92',
                                             'avg_individual_team_against': '1.79',
                                             'avg_overall_total': '2.71',
                                             'games_played': '38',
                                             'points': '33',
                                             'team_name': 'Stoke',
                                             'team_position': '25'},
                                            {'avg_individual_team': '0.92',
                                             'avg_individual_team_against': '2.02',
                                             'avg_overall_total': '2.94',
                                             'games_played': '50',
                                             'points': '33',
                                             'team_name': 'Watford',
                                             'team_position': '26'},
                                            {'avg_individual_team': '0.9',
                                             'avg_individual_team_against': '2.06',
                                             'avg_overall_total': '2.96',
                                             'games_played': '50',
                                             'points': '30',
                                             'team_name': 'Southampton',
                                             'team_position': '27'},
                                            {'avg_individual_team': '0.62',
                                             'avg_individual_team_against': '1.76',
                                             'avg_overall_total': '2.38',
                                             'games_played': '50',
                                             'points': '29',
                                             'team_name': 'Huddersfield',
                                             'team_position': '28'},
                                            {'avg_individual_team': '0.5',
                                             'avg_individual_team_against': '2.22',
                                             'avg_overall_total': '2.72',
                                             'games_played': '50',
                                             'points': '25',
                                             'team_name': 'Norwich',
                                             'team_position': '29'}]},
               'previous_season': {'goals': [{'avg_individual_team': '2.6',
                                              'avg_individual_team_against': '0.84',
                                              'avg_overall_total': '3.44',
                                              'games_played': '50',
                                              'points': '119',
                                              'team_name': 'Man '
                                                           'City',
                                              'team_position': '1'},
                                             {'avg_individual_team': '2.12',
                                              'avg_individual_team_against': '1.24',
                                              'avg_overall_total': '3.36',
                                              'games_played': '50',
                                              'points': '102',
                                              'team_name': 'Arsenal',
                                              'team_position': '2'},
                                             {'avg_individual_team': '1.98',
                                              'avg_individual_team_against': '1.06',
                                              'avg_overall_total': '3.04',
                                              'games_played': '50',
                                              'points': '99',
                                              'team_name': 'Liverpool',
                                              'team_position': '3'},
                                             {'avg_individual_team': '1.64',
                                              'avg_individual_team_against': '0.98',
                                              'avg_overall_total': '2.62',
                                              'games_played': '50',
                                              'points': '92',
                                              'team_name': 'Newcastle',
                                              'team_position': '4'},
                                             {'avg_individual_team': '1.42',
                                              'avg_individual_team_against': '1.32',
                                              'avg_overall_total': '2.74',
                                              'games_played': '50',
                                              'points': '87',
                                              'team_name': 'Man '
                                                           'Utd',
                                              'team_position': '5'},
                                             {'avg_individual_team': '1.98',
                                              'avg_individual_team_against': '1.42',
                                              'avg_overall_total': '3.4',
                                              'games_played': '50',
                                              'points': '86',
                                              'team_name': 'Tottenham',
                                              'team_position': '6'},
                                             {'avg_individual_team': '1.58',
                                              'avg_individual_team_against': '1.2',
                                              'avg_overall_total': '2.78',
                                              'games_played': '50',
                                              'points': '81',
                                              'team_name': 'Brentford',
                                              'team_position': '7'},
                                             {'avg_individual_team': '1.78',
                                              'avg_individual_team_against': '1.34',
                                              'avg_overall_total': '3.12',
                                              'games_played': '50',
                                              'points': '80',
                                              'team_name': 'Brighton',
                                              'team_position': '8'},
                                             {'avg_individual_team': '1.32',
                                              'avg_individual_team_against': '1.26',
                                              'avg_overall_total': '2.58',
                                              'games_played': '50',
                                              'points': '73',
                                              'team_name': 'Aston '
                                                           'Villa',
                                              'team_position': '9'},
                                             {'avg_individual_team': '1.22',
                                              'avg_individual_team_against': '1.24',
                                              'avg_overall_total': '2.46',
                                              'games_played': '50',
                                              'points': '65',
                                              'team_name': 'Chelsea',
                                              'team_position': '10'},
                                             {'avg_individual_team': '1.08',
                                              'avg_individual_team_against': '1.16',
                                              'avg_overall_total': '2.24',
                                              'games_played': '50',
                                              'points': '64',
                                              'team_name': 'Crystal '
                                                           'Palace',
                                              'team_position': '11'},
                                             {'avg_individual_team': '1.14',
                                              'avg_individual_team_against': '1.44',
                                              'avg_overall_total': '2.58',
                                              'games_played': '50',
                                              'points': '54',
                                              'team_name': 'West '
                                                           'Ham',
                                              'team_position': '12'},
                                             {'avg_individual_team': '1.46',
                                              'avg_individual_team_against': '1.64',
                                              'avg_overall_total': '3.1',
                                              'games_played': '50',
                                              'points': '53',
                                              'team_name': 'Leicester',
                                              'team_position': '13'},
                                             {'avg_individual_team': '0.98',
                                              'avg_individual_team_against': '1.52',
                                              'avg_overall_total': '2.5',
                                              'games_played': '50',
                                              'points': '53',
                                              'team_name': 'Everton',
                                              'team_position': '14'},
                                             {'avg_individual_team': '1.45',
                                              'avg_individual_team_against': '1.39',
                                              'avg_overall_total': '2.84',
                                              'games_played': '38',
                                              'points': '52',
                                              'team_name': 'Fulham',
                                              'team_position': '15'},
                                             {'avg_individual_team': '0.9',
                                              'avg_individual_team_against': '1.6',
                                              'avg_overall_total': '2.5',
                                              'games_played': '50',
                                              'points': '52',
                                              'team_name': 'Wolves',
                                              'team_position': '16'},
                                             {'avg_individual_team': '1.22',
                                              'avg_individual_team_against': '1.94',
                                              'avg_overall_total': '3.16',
                                              'games_played': '50',
                                              'points': '46',
                                              'team_name': 'Leeds',
                                              'team_position': '17'},
                                             {'avg_individual_team': '0.97',
                                              'avg_individual_team_against': '1.87',
                                              'avg_overall_total': '2.84',
                                              'games_played': '38',
                                              'points': '39',
                                              'team_name': 'Bournemouth',
                                              'team_position': '18'},
                                             {'avg_individual_team': '1',
                                              'avg_individual_team_against': '1.79',
                                              'avg_overall_total': '2.79',
                                              'games_played': '38',
                                              'points': '38',
                                              'team_name': 'Nottingham '
                                                           'Forest',
                                              'team_position': '19'},
                                             {'avg_individual_team': '0.89',
                                              'avg_individual_team_against': '1.39',
                                              'avg_overall_total': '2.29',
                                              'games_played': '38',
                                              'points': '35',
                                              'team_name': 'Burnley',
                                              'team_position': '20'},
                                             {'avg_individual_team': '0.9',
                                              'avg_individual_team_against': '2.06',
                                              'avg_overall_total': '2.96',
                                              'games_played': '50',
                                              'points': '30',
                                              'team_name': 'Southampton',
                                              'team_position': '21'},
                                             {'avg_individual_team': '0.89',
                                              'avg_individual_team_against': '2.03',
                                              'avg_overall_total': '2.92',
                                              'games_played': '38',
                                              'points': '23',
                                              'team_name': 'Watford',
                                              'team_position': '22'},
                                             {'avg_individual_team': '0.61',
                                              'avg_individual_team_against': '2.21',
                                              'avg_overall_total': '2.82',
                                              'games_played': '38',
                                              'points': '22',
                                              'team_name': 'Norwich',
                                              'team_position': '23'}]}}


from graph.matrix_data_generator import MatrixDataGenerator
from pprint import pprint

matrix = MatrixDataGenerator(league_data=league_data,
                             last_year_data=last_year_data,
                             home_command_name='Brentford',
                             away_command_name='West Ham')
matrix_data = matrix.generate_matrix_data()
pprint(matrix_data)