stats_dict = {
    'Голы': 'goals',
    'Угловые': 'corners',
    'ЖК': 'yellow cards',
    'Фолы': 'fouls',
    'Уд. в створ': 'shots on goal',
    'Офсайды': 'offsides',
    'Ауты': 'throw-ins',
    'Удары от ворот': 'goal kicks',
    'Удары': 'shots',
}

exclude_list = [
    'union',
    'united',
    'town',
    'hapoel',
    'city',
    'county',
    'olympique',
    'west',
    'deportivo',
    'maccabi',
    'port',
    'santa',
    'rovers',
    'central',
    'sport',
    'nicosia',
    'wanderers',
    'kings',
    'borac',
    'south',
    'atletico',
    'saint',
    'moscow'
]
